#version: '3.8'

services:
  web:
    build: . 
    image: jamesnyamburi/django-hospital-app:latest
    ports:
      - "8080:8000"
    # environment:
    

    volumes:
      - .:/app
    command: >
      sh -c "python manage.py migrate &&
             python manage.py collectstatic --noinput &&
             gunicorn --bind 0.0.0.0:8000 hospitalmanagement.wsgi:application"

  # Redis Image for caching
  #redis:
  #image: redis:alpine
  #ports: 
  #- "6379:6379"


