# Generated by Django 3.0.5 on 2025-03-09 07:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0019_auto_20250309_0704'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='appointmentDate',
        ),
        migrations.AddField(
            model_name='appointment',
            name='book_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='appointment',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
